//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraSua.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONSUKIEN
    {
        public int MSHD { get; set; }
        public int MASK { get; set; }
        public string GIAMGIA { get; set; }
        public int MLSK { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SUKIEN SUKIEN { get; set; }
    }
}
