//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraSua.Model
{
    using QuanLyTraSua.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class NGUYENLIEU : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUYENLIEU()
        {
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETPHIEUXUATs = new HashSet<CHITIETPHIEUXUAT>();
        }

        public int MSNL { get; set; }

        private string _TENNL { get; set; }
        public string TENNL { get => _TENNL; set { _TENNL = value; OnPropertyChanged(); } }

        private string _DVT { get; set; }
        public string DVT { get => _DVT; set { _DVT = value; OnPropertyChanged(); } }

        private int _GIABAN { get; set; }
        public int GIABAN { get => _GIABAN; set { _GIABAN = value; OnPropertyChanged(); } }

        public int MSNCC { get; set; }

        public bool ACTIVE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
